package polimi.ingsw.View.userView.utilities.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN,
    GAME_ID_NOT_EXISTS,
    GENERIC_ERROR_WHEN_ENTRYING_GAME,
    PLAYER_IS_READY_TO_START,
    COMMON_CARD_EXTRACTED,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    GRABBED_TILE,
    GRABBED_TILE_NOT_CORRECT,
    POSITIONED_TILE,
    NEXT_TURN,
    ADDED_POINT,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED

}
