package polimi.ingsw.View.userView.Events;

public enum EventType {
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN,
    GAME_ID_NOT_EXISTS,
    NO_GAMES_AVAILABLE_TO_JOIN,
    PLAYER_IS_READY_TO_START,
    COMMON_CARD_EXTRACTED,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    GRABBED_TILE,
    GRABBED_TILE_NOT_CORRECT,
    POSITIONED_TILE,
    NEXT_TURN,
    ADDED_POINT,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED

}
